### ISSUE TITLE
Make the algorithm non-destructive

### ISSUE THREAD

**Issue by ralt** [benjamingr/RegExp.escape#16]
Instead of appending characters to `cuList`, can't you create a new list? Basically, make the algorithm non-destructive at each iteration.

I guess it's more so that the algorithm can be recursive/more elegant (<sup>citation needed</sup>). I'm not sure whether it's an implementation detail, nor how the spec should be written.

**Comment by benjamingr** [comment]
Thanks for the feedback.

The algorithm isn't destructive - note that first a `cpList` is created from the code points and then a new list `cuList` (different list) is created. The algorithm doesn't alter the input. 

Implementation wise - no lists would probably actually be allocated - this is done in the polyfill with a single `.replace`, implementations will likely do a single iteration on the chars and create a new string from chars without treating code points since all the characters currently escaped are a single code unit.
