### ISSUE TITLE
Create a table of every escaped character and "why"

### ISSUE THREAD

**Issue by domenic** [benjamingr/RegExp.escape#31]
I've asked for this a couple times, but I think it's crucial to forward progress, especially as people debate additions to the current spec.

Here is a start:

|char|reason|
---|----
|^|new RegExp("^") => syntax error; new RegExp("\\^") => matches the string "^"|

**Comment by benjamingr** [comment]
Will do

**Comment by benjamingr** [comment]
@domenic  done :)

**Comment by domenic** [comment]
Yay! Might want to give it a proofread, but overall very helpful.

**Comment by jbnicolai** [comment]
If I can weigh in, I think we've nailed the exact list over at https://github.com/sindresorhus/escape-string-regexp/blob/master/index.js#L3

**Comment by jbnicolai** [comment]
Nevermind, the two seem to already be a 1 on 1 match - so kudos to @benjamingr ;)

**Comment by bergus** [comment]
The entry for `?` should mention the usage of the syntax character in groups, not only as a quantifier.

The `WhiteSpace` entry in the extended safe set is currently a copy of the `/` entry. It should rather link to #30.

The escaping of hex characters in the beginning should be added, so that they don't extend decimal or unicode escape sequences.

**Comment by benjamingr** [comment]
@bergus can you open a separate issue please? (Pull request would also be welcome)

**Comment by cscott** [comment]
Agreed with @bergus.

I'd also like to see the "safe with extra escape set" section reference @bergus' rationale for this set.
